### ISSUE TITLE
Enable support for forks of WLED

### ISSUE THREAD

**Issue by U1F984** [frenck/python-wled#1597]
# Problem/Motivation

Supports of WLED will never be supported by this library. I create this issue to document a workaround I've found for other people struggling with this issue.

The workaround involves using this component: https://github.com/amitfin/patch.
In my setup using Homeassistant OS: 

1. Login to OS using `login` on command line, execute `docker exec -it homeassistant bash` to get a shell. This can also be done via SSH addon if I'm not mistaken.
2. Create directory structure in `/config`: `patches/base` and `patches/patch`.
3. Copy `models.py` from `/usr/ local/lib/python3.13/site-packages/wled` to base and patch directory (could be a later python version as well)
4. Edit file in patch directory, replace version check: `if (version := d.get("info", {}).get("ver")) and version < MIN_REQUIRED_VERSION:` with `if False:`
5. Add patch config to `configuration.yaml` (note that `{site-packages}` will be replaced by the correct path automatically):
```
# Patch HACS addon
patch:
  delay: 60
  restart: true
  files:
    - name: models.py
      base: /config/patches/base
      destination: "{site-packages}/wled"
      patch: /config/patches/patch
```
6. Restart homeassistant

## Expected behavior

WLED supports forks, but this is not going to be implemented, see #1447.

## Actual behavior

WLED refuses to accept fork versions.

## Steps to reproduce

Setup e.g. the WLED MoonModules fork for audio integration.

## Proposed changes

None, see #1447. Alternatively it could be unsupported but still possible using a configuration flag.
